//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj_Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sinertica_RLRobotEntities : DbContext
    {
        public sinertica_RLRobotEntities()
            : base("name=sinertica_RLRobotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rl_Robot> Rl_Robot { get; set; }
        public virtual DbSet<RI_Role> RI_Role { get; set; }
        public virtual DbSet<RI_Users> RI_Users { get; set; }
    }
}
