//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj_Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RI_Users
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
    
        public virtual RI_Role RI_Role { get; set; }
    }
}
