//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj_Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rl_Robot
    {
        public System.Guid ID { get; set; }
        public string UserWeb { get; set; }
        public string PasswordWeb { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LoginUrl { get; set; }
        public string NodeName { get; set; }
        public System.DateTime TimeGenReports { get; set; }
        public System.DateTime TimeDownReports { get; set; }
        public int Timespan { get; set; }
        public string LocalFolder { get; set; }
        public string Message { get; set; }
        public Nullable<int> StatusClient { get; set; }
        public Nullable<int> CodError { get; set; }
        public Nullable<int> CodRequest { get; set; }
        public Nullable<System.DateTime> DateSubscribe { get; set; }
        public Nullable<System.DateTime> FechaHoraUltimoReporte { get; set; }
        public string EmailNotificaciones { get; set; }
        public string Token { get; set; }
    }
}
